# docker run -d --rm --name mongo-container -p 27017:27017 -v mongodbdata:/data/db mongo

version: '3.8' # Docker-compose version

services:
  # Services to run
  mongo:
    # Service name
    image: mongo # Official image from Docker Hub
    container_name: mongo-container
    ports:
      # Ports to expose
      - "27017:27017" # Host:Container external:internal port
    volumes:
      # Volumes to persist data
      - mongodbdata:/data/db # Persist data in mongodbdata volume created below

  rabbitmq:
    # Service name
    image: rabbitmq:management
    container_name: rabbitmq-container
    ports:
      # Ports to expose
      - "5672:5672" # Host:Container external:internal ports to communicate to RabbitMQ
      - "15672:15672" # Host:Container external:internal ports to go to portal of RabbitMQ
    volumes:
      # Volumes to persist data
      - rabbitmqdata:/var/lib/rabbitmq # Persist data in rabbitmqdata volume created below
    hostname: rabbitmq-container # Hostname of the container

volumes:
  # Volumes to persist data
  mongodbdata: # Volume name
  rabbitmqdata: # Volume name
